In [42]:
import pandas as pd
import urllib
from urllib import request
import featuretools as ft
import numpy as np

In [43]:
url = "https://raw.githubusercontent.com/LuisM78/Appliances-energy-prediction-data/master/energydata_complete.csv"
df = pd.read_csv(url)

In [44]:
df.head(10)

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.890000,47.596667,19.20,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.500000,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.890000,46.693333,19.20,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.600000,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.890000,46.300000,19.20,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.700000,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.890000,46.066667,19.20,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.800000,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.890000,46.333333,19.20,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.900000,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
5,2016-01-11 17:50:00,50,40,19.890000,46.026667,19.20,44.500000,19.79,44.933333,18.890000,...,17.000000,45.29,6.016667,734.000000,92.000000,5.333333,43.833333,4.800000,44.919484,44.919484
6,2016-01-11 18:00:00,60,50,19.890000,45.766667,19.20,44.500000,19.79,44.900000,18.890000,...,17.000000,45.29,5.900000,734.100000,92.000000,5.000000,40.000000,4.700000,47.233763,47.233763
7,2016-01-11 18:10:00,60,50,19.856667,45.560000,19.20,44.500000,19.73,44.900000,18.890000,...,17.000000,45.29,5.916667,734.166667,91.833333,5.166667,40.000000,4.683333,33.039890,33.039890
8,2016-01-11 18:20:00,60,40,19.790000,45.597500,19.20,44.433333,19.73,44.790000,18.890000,...,17.000000,45.29,5.933333,734.233333,91.666667,5.333333,40.000000,4.666667,31.455702,31.455702
9,2016-01-11 18:30:00,70,40,19.856667,46.090000,19.23,44.400000,19.79,44.863333,18.890000,...,17.000000,45.29,5.950000,734.300000,91.500000,5.500000,40.000000,4.650000,3.089314,3.089314

In [9]:
data1 = df
data1 = data1.drop(['Appliances'],axis=1)
data1

,date,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,...,17.033333,45.530000,6.600000,733.500000,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,2016-01-11 17:10:00,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,...,17.066667,45.560000,6.483333,733.600000,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,2016-01-11 17:20:00,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,...,17.000000,45.500000,6.366667,733.700000,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,2016-01-11 17:30:00,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,...,17.000000,45.400000,6.250000,733.800000,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,2016-01-11 17:40:00,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,...,17.000000,45.400000,6.133333,733.900000,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
5,2016-01-11 17:50:00,40,19.890000,46.026667,19.200000,44.500000,19.790000,44.933333,18.890000,45.730000,...,17.000000,45.290000,6.016667,734.000000,92.000000,5.333333,43.833333,4.800000,44.919484,44.919484
6,2016-01-11 18:00:00,50,19.890000,45.766667,19.200000,44.500000,19.790000,44.900000,18.890000,45.790000,...,17.000000,45.290000,5.900000,734.100000,92.000000,5.000000,40.000000,4.700000,47.233763,47.233763
7,2016-01-11 18:10:00,50,19.856667,45.560000,19.200000,44.500000,19.730000,44.900000,18.890000,45.863333,...,17.000000,45.290000,5.916667,734.166667,91.833333,5.166667,40.000000,4.683333,33.039890,33.039890
8,2016-01-11 18:20:00,40,19.790000,45.597500,19.200000,44.433333,19.730000,44.790000,18.890000,45.790000,...,17.000000,45.290000,5.933333,734.233333,91.666667,5.333333,40.000000,4.666667,31.455702,31.455702
9,2016-01-11 18:30:00,40,19.856667,46.090000,19.230000,44.400000,19.790000,44.863333,18.890000,46.096667,...,17.000000,45.290000,5.950000,734.300000,91.500000,5.500000,40.000000,4.650000,3.089314,3.089314
10,2016-01-11 18:40:00,70,19.926667,45.863333,19.356667,44.400000,19.790000,44.900000,18.890000,46.430000,...,17.000000,45.290000,5.966667,734.366667,91.333333,5.666667,40.000000,4.633333,10.298729,10.298729
11,2016-01-11 18:50:00,60,20.066667,46.396667,19.426667,44.400000,19.790000,44.826667,19.000000,46.430000,...,16.890000,45.290000,5.983333,734.433333,91.166667,5.833333,40.000000,4.616667,8.827838,8.827838
12,2016-01-11 19:00:00,50,20.133333,48.000000,19.566667,44.400000,19.890000,44.900000,19.000000,46.363333,...,16.963333,45.290000,6.000000,734.500000,91.000000,6.000000,40.000000,4.600000,34.351142,34.351142
13,2016-01-11 19:10:00,40,20.260000,52.726667,19.730000,45.100000,19.890000,45.493333,19.000000,47.223333,...,16.890000,45.326667,6.000000,734.616667,90.500000,6.000000,40.000000,4.516667,19.205186,19.205186
14,2016-01-11 19:20:00,10,20.426667,55.893333,19.856667,45.833333,20.033333,47.526667,19.000000,48.696667,...,16.890000,45.345000,6.000000,734.733333,90.000000,6.000000,40.000000,4.433333,38.492071,38.492071
15,2016-01-11 19:30:00,10,20.566667,53.893333,20.033333,46.756667,20.100000,48.466667,19.000000,48.490000,...,16.890000,45.326667,6.000000,734.850000,89.500000,6.000000,40.000000,4.350000,24.884962,24.884962
16,2016-01-11 19:40:00,10,20.730000,52.660000,20.166667,47.223333,20.200000,48.530000,18.926667,48.156667,...,16.890000,45.290000,6.000000,734.966667,89.000000,6.000000,40.000000,4.266667,35.880925,35.880925
17,2016-01-11 19:50:00,30,20.856667,53.660000,20.200000,47.056667,20.200000,48.447500,18.890000,47.963333,...,16.890000,45.290000,6.000000,735.083333,88.500000,6.000000,40.000000,4.183333,49.595305,49.595305
18,2016-01-11 20:00:00,30,20.890000,51.193333,20.200000,46.330000,20.200000,48.193333,18.963333,48.630000,...,16.890000,45.200000,6.000000,735.200000,88.000000,6.000000,40.000000,4.100000,19.001759,19.001759
19,2016-01-11 20:10:00,40,20.890000,49.800000,20.200000,46.026667,20.166667,47.633333,19.033333,49.500000,...,16.890000,45.200000,6.000000,735.233333,87.833333,6.000000,40.000000,4.066667,38.872261,38.872261
20,2016-01-11 20:20:00,20,20.890000,48.433333,20.200000,45.722500,20.166667,47.300000,19.175000,49.947500,...,16.890000,45.126667,6.000000,735.266667,87.666667,6.000000,40.000000,4.033333,46.735262,46.735262
21,2016-01-11 20:30:00,40,20.963333,47.633333,20.260000,45.530000,20.200000,47.026667,19.260000,49.696667,...,16.890000,45.126667,6.000000,735.300000,87.500000,6.000000,40.000000,4.000000,10.607126,10.607126
22,2016-01-11 20:40:00,40,21.033333,47.063333,20.290000,45.223333,20.260000,46.826667,19.323333,49.166667,...,16.890000,45.060000,6.000000,735.333333,87.333333,6.000000,40.000000,3.966667,32.583688,32.583688
23,2016-01-11 20:50:00,40,21.100000,46.596667,20.356667,44.963333,20.290000,46.633333,19.390000,48.426667,...,16.890000,45.000000,6.000000,735.366667,87.166667,6.000000,40.000000,3.933333,6.277755,6.277755
24,2016-01-11 21:00:00,30,21.133333,46.060000,20.426667,44.760000,20.290000,46.433333,19.390000,48.193333,...,16.890000,44.966667,6.000000,735.400000,87.000000,6.000000,40.000000,3.900000,13.361033,13.361033
25,2016-01-11 21:10:00,20,21.200000,45.800000,20.500000,44.760000,20.390000,46.223333,19.390000,47.800000,...,16.890000,44.900000,5.933333,735.466667,87.166667,6.000000,40.000000,3.866667,19.305705,19.305705
26,2016-01-11 21:20:00,30,21.290000,45.900000,20.533333,45.090000,20.390000,46.090000,19.390000,47.560000,...,16.890000,44.790000,5.866667,735.533333,87.333333,6.000000,40.000000,3.833333,0.669517,0.669517
27,2016-01-11 21:30:00,20,21.356667,45.826667,20.666667,45.163333,20.390000,46.090000,19.390000,47.500000,...,16.890000,44.790000,5.800000,735.600000,87.500000,6.000000,40.000000,3.800000,19.119398,19.119398
28,2016-01-11 21:40:00,20,21.390000,45.690000,20.700000,45.060000,20.390000,46.090000,19.426667,47.993333,...,16.890000,44.700000,5.733333,735.666667,87.666667,6.000000,40.000000,3.766667,43.484542,43.484542
29,2016-01-11 21:50:00,20,21.500000,45.333333,20.700000,44.933333,20.390000,46.060000,19.566667,48.466667,...,16.890000,44.700000,5.666667,735.733333,87.833333,6.000000,40.000000,3.733333,17.017450,17.017450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19705,2016-05-27 13:10:00,0,25.033333,48.363333,26.528571,40.595714,28.496667,41.900000,24.500000,45.066667,...,23.100000,46.500000,21.250000,756.050000,59.833333,1.166667,23.666667,13.100000,32.420348,32.420348
19706,2016-05-27 13:20:00,0,25.166667,48.156667,26.600000,40.940000,28.290000,41.966667,24.500000,45.333333,...,23.100000,46.500000,21.400000,756.000000,59.666667,1.333333,23.333333,13.200000,49.189027,49.189027
19707,2016-05-27 13:30:00,0,25.323333,47.930000,26.600000,41.012857,28.200000,42.090000,24.533333,45.566667,...,23.100000,46.522500,21.550000,755.950000,59.500000,1.500000,23.000000,13.300000,15.081162,15.081162
19708,2016-05-27 13:40:00,0,25.390000,47.656667,26.600000,41.036000,28.200000,42.030000,24.600000,45.760000,...,23.100000,46.530000,21.700000,755.900000,59.333333,1.666667,22.666667,13.400000,45.226866,45.226866
19709,2016-05-27 13:50:00,0,25.500000,47.133333,26.600000,41.000000,28.200000,41.796667,24.600000,45.790000,...,23.100000,46.530000,21.850000,755.850000,59.166667,1.833333,22.333333,13.500000,5.773431,5.773431
19710,2016-05-27 14:00:00,10,25.500000,47.060000,26.540000,41.000000,28.200000,41.530000,24.600000,45.863333,...,23.100000,46.530000,22.000000,755.800000,59.000000,2.000000,22.000000,13.600000,41.515044,41.515044
19711,2016-05-27 14:10:00,0,25.600000,46.990000,26.512500,41.203750,28.200000,41.590000,24.633333,46.030000,...,23.100000,46.530000,21.966667,755.800000,59.000000,2.000000,21.833333,13.550000,19.540642,19.540642
19712,2016-05-27 14:20:00,0,25.600000,46.730000,26.437143,41.384286,28.426667,41.430000,24.700000,46.090000,...,23.100000,46.590000,21.933333,755.800000,59.000000,2.000000,21.666667,13.500000,16.977597,16.977597
19713,2016-05-27 14:30:00,0,25.566667,46.633333,26.370000,41.378000,28.566667,41.156667,24.700000,45.966667,...,23.100000,46.626667,21.900000,755.800000,59.000000,2.000000,21.500000,13.450000,8.991420,8.991420
19714,2016-05-27 14:40:00,0,25.500000,46.360000,26.318571,41.264286,28.566667,40.663333,24.700000,45.826667,...,23.100000,46.700000,21.866667,755.800000,59.000000,2.000000,21.333333,13.400000,40.409885,40.409885
19715,2016-05-27 14:50:00,0,25.500000,46.060000,26.350000,41.000000,28.426667,40.590000,24.666667,45.526667,...,23.100000,46.590000,21.833333,755.800000,59.000000,2.000000,21.166667,13.350000,37.889086,37.889086
19716,2016-05-27 15:00:00,0,25.500000,45.933333,26.277143,41.000000,28.356667,40.560000,24.666667,45.400000,...,23.100000,46.590000,21.800000,755.800000,59.000000,2.000000,21.000000,13.300000,17.123315,17.123315
19717,2016-05-27 15:10:00,0,25.500000,45.760000,26.200000,41.000000,28.290000,40.433333,24.700000,45.363333,...,23.133333,46.590000,21.966667,755.750000,58.333333,2.000000,21.333333,13.283333,24.058432,24.058432
19718,2016-05-27 15:20:00,0,25.500000,45.626667,26.171429,41.000000,28.260000,40.260000,24.700000,45.230000,...,23.133333,46.590000,22.133333,755.700000,57.666667,2.000000,21.666667,13.266667,9.538671,9.538671
19719,2016-05-27 15:30:00,0,25.500000,45.590000,26.100000,41.000000,28.200000,40.126667,24.700000,45.163333,...,23.166667,46.590000,22.300000,755.650000,57.000000,2.000000,22.000000,13.250000,30.020685,30.020685
19720,2016-05-27 15:40:00,0,25.500000,45.522500,26.100000,41.051429,28.200000,40.200000,24.700000,45.163333,...,23.100000,46.590000,22.466667,755.600000,56.333333,2.000000,22.333333,13.233333,23.851737,23.851737
19721,2016-05-27 15:50:00,0,25.500000,45.633333,26.080000,41.196000,28.133333,40.260000,24.700000,45.300000,...,23.200000,46.590000,22.633333,755.550000,55.666667,2.000000,22.666667,13.216667,47.981309,47.981309
19722,2016-05-27 16:00:00,0,25.500000,45.730000,26.000000,41.428571,28.100000,40.433333,24.700000,45.433333,...,23.200000,46.590000,22.800000,755.500000,55.000000,2.000000,23.000000,13.200000,18.215602,18.215602
19723,2016-05-27 16:10:00,0,25.500000,45.790000,26.000000,41.590000,28.100000,40.560000,24.700000,45.500000,...,23.160000,46.590000,22.833333,755.450000,55.000000,2.166667,22.833333,13.233333,38.751594,38.751594
19724,2016-05-27 16:20:00,0,25.500000,45.933333,26.000000,41.652857,28.000000,40.700000,24.700000,45.466667,...,23.200000,46.621429,22.866667,755.400000,55.000000,2.333333,22.666667,13.266667,32.306224,32.306224
19725,2016-05-27 16:30:00,0,25.426667,46.060000,26.000000,41.700000,28.000000,40.760000,24.700000,45.400000,...,23.200000,46.700000,22.900000,755.350000,55.000000,2.500000,22.500000,13.300000,23.009520,23.009520
19726,2016-05-27 16:40:00,0,25.500000,46.530000,26.000000,41.725714,27.856667,40.500000,24.700000,45.500000,...,23.200000,46.652857,22.933333,755.300000,55.000000,2.666667,22.333333,13.333333,25.296732,25.296732
19727,2016-05-27 16:50:00,0,25.500000,47.456667,26.000000,42.320000,27.663333,40.693333,24.700000,45.560000,...,23.200000,46.718000,22.966667,755.250000,55.000000,2.833333,22.166667,13.366667,1.796395,1.796395
19728,2016-05-27 17:00:00,0,25.600000,47.193333,25.968571,42.528571,27.390000,41.030000,24.700000,45.626667,...,23.200000,46.751429,23.000000,755.200000,55.000000,3.000000,22.000000,13.400000,18.248201,18.248201
19729,2016-05-27 17:10:00,0,25.533333,46.860000,25.978000,42.534000,27.323333,41.090000,24.700000,45.626667,...,23.200000,46.745000,22.866667,755.200000,55.333333,3.166667,22.833333,13.366667,16.966162,16.966162
19730,2016-05-27 17:20:00,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,...,23.200000,46.790000,22.733333,755.200000,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,2016-05-27 17:30:00,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,...,23.200000,46.790000,22.600000,755.200000,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,2016-05-27 17:40:00,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,...,23.200000,46.790000,22.466667,755.200000,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,2016-05-27 17:50:00,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,...,23.200000,46.817500,22.333333,755.200000,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,2016-05-27 18:00:00,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,...,23.200000,46.845000,22.200000,755.200000,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [5]:
entities = {
    "energydata" : (df, "id")
}

In [7]:
es=ft.EntitySet("entityset", entities)

2018-11-03 23:47:58,335 featuretools.entityset - WARNING    index id not found in dataframe, creating new integer column

In [9]:
es["energydata"].variables

[<Variable: id (dtype = index)>,
 <Variable: date (dtype: datetime, format: None)>,
 <Variable: Appliances (dtype = numeric)>,
 <Variable: lights (dtype = numeric)>,
 <Variable: T1 (dtype = numeric)>,
 <Variable: RH_1 (dtype = numeric)>,
 <Variable: T2 (dtype = numeric)>,
 <Variable: RH_2 (dtype = numeric)>,
 <Variable: T3 (dtype = numeric)>,
 <Variable: RH_3 (dtype = numeric)>,
 <Variable: T4 (dtype = numeric)>,
 <Variable: RH_4 (dtype = numeric)>,
 <Variable: T5 (dtype = numeric)>,
 <Variable: RH_5 (dtype = numeric)>,
 <Variable: T6 (dtype = numeric)>,
 <Variable: RH_6 (dtype = numeric)>,
 <Variable: T7 (dtype = numeric)>,
 <Variable: RH_7 (dtype = numeric)>,
 <Variable: T8 (dtype = numeric)>,
 <Variable: RH_8 (dtype = numeric)>,
 <Variable: T9 (dtype = numeric)>,
 <Variable: RH_9 (dtype = numeric)>,
 <Variable: T_out (dtype = numeric)>,
 <Variable: Press_mm_hg (dtype = numeric)>,
 <Variable: RH_out (dtype = numeric)>,
 <Variable: Windspeed (dtype = numeric)>,
 <Variable: Visibility (dtype = numeric)>,
 <Variable: Tdewpoint (dtype = numeric)>,
 <Variable: rv1 (dtype = numeric)>,
 <Variable: rv2 (dtype = numeric)>]

In [10]:
es = es.normalize_entity(base_entity_id="energydata",
                             new_entity_id="lights",
                             index="Appliances",additional_variables=["T2", "T5", "T7"])

In [15]:
es["lights"].variables

[<Variable: Appliances (dtype = index)>,
 <Variable: T2 (dtype = numeric)>,
 <Variable: T5 (dtype = numeric)>,
 <Variable: T7 (dtype = numeric)>]

In [20]:
es

Entityset: entityset
  Entities:
    energydata [Rows: 19735, Columns: 27]
    lights [Rows: 92, Columns: 4]
  Relationships:
    energydata.Appliances -> lights.Appliances

In [21]:
new_relationship = ft.Relationship(es["lights"]["Appliances"],
                                     es["energydata"]["Appliances"])

In [25]:
feature_matrix, feature_defs = ft.dfs(entityset=es,target_entity="energydata", max_depth=3, verbose=1)

Built 185 features
Elapsed: 00:09 | Remaining: 00:00 | Progress: 100%|██████████████████████████████████████████| Calculated: 11/11 chunks

In [26]:
feature_matrix

,Appliances,lights,T1,RH_1,RH_2,T3,RH_3,T4,RH_4,RH_5,...,lights.MEAN(energydata.rv2),lights.COUNT(energydata),lights.NUM_UNIQUE(energydata.DAY(date)),lights.NUM_UNIQUE(energydata.YEAR(date)),lights.NUM_UNIQUE(energydata.MONTH(date)),lights.NUM_UNIQUE(energydata.WEEKDAY(date)),lights.MODE(energydata.DAY(date)),lights.MODE(energydata.YEAR(date)),lights.MODE(energydata.MONTH(date)),lights.MODE(energydata.WEEKDAY(date))
id,,,,,,,,,,,,,,,,,,,,,
0,60,30,19.890000,47.596667,44.790000,19.790000,44.730000,19.000000,45.566667,55.200000,...,25.181673,3282,31,1,5,7,12,2016,4,1
1,60,30,19.890000,46.693333,44.722500,19.790000,44.790000,19.000000,45.992500,55.200000,...,25.181673,3282,31,1,5,7,12,2016,4,1
2,50,30,19.890000,46.300000,44.626667,19.790000,44.933333,18.926667,45.890000,55.090000,...,25.104459,4368,31,1,5,7,19,2016,4,1
3,50,40,19.890000,46.066667,44.590000,19.790000,45.000000,18.890000,45.723333,55.090000,...,25.104459,4368,31,1,5,7,19,2016,4,1
4,60,40,19.890000,46.333333,44.530000,19.790000,45.000000,18.890000,45.530000,55.090000,...,25.181673,3282,31,1,5,7,12,2016,4,1
5,50,40,19.890000,46.026667,44.500000,19.790000,44.933333,18.890000,45.730000,55.030000,...,25.104459,4368,31,1,5,7,19,2016,4,1
6,60,50,19.890000,45.766667,44.500000,19.790000,44.900000,18.890000,45.790000,54.966667,...,25.181673,3282,31,1,5,7,12,2016,4,1
7,60,50,19.856667,45.560000,44.500000,19.730000,44.900000,18.890000,45.863333,54.900000,...,25.181673,3282,31,1,5,7,12,2016,4,1
8,60,40,19.790000,45.597500,44.433333,19.730000,44.790000,18.890000,45.790000,55.000000,...,25.181673,3282,31,1,5,7,12,2016,4,1
9,70,40,19.856667,46.090000,44.400000,19.790000,44.863333,18.890000,46.096667,55.000000,...,24.501307,1560,31,1,5,7,25,2016,4,2
10,230,70,19.926667,45.863333,44.400000,19.790000,44.900000,18.890000,46.430000,55.000000,...,26.142286,82,29,1,5,7,16,2016,2,0
11,580,60,20.066667,46.396667,44.400000,19.790000,44.826667,19.000000,46.430000,55.000000,...,17.835453,11,10,1,5,6,28,2016,2,0
12,430,50,20.133333,48.000000,44.400000,19.890000,44.900000,19.000000,46.363333,55.090000,...,21.247191,25,17,1,5,6,1,2016,2,0
13,250,40,20.260000,52.726667,45.100000,19.890000,45.493333,19.000000,47.223333,55.163333,...,23.687579,77,28,1,5,7,13,2016,2,5
14,100,10,20.426667,55.893333,45.833333,20.033333,47.526667,19.000000,48.696667,55.500000,...,25.172715,978,31,1,5,7,14,2016,2,6
15,100,10,20.566667,53.893333,46.756667,20.100000,48.466667,19.000000,48.490000,56.042500,...,25.172715,978,31,1,5,7,14,2016,2,6
16,90,10,20.730000,52.660000,47.223333,20.200000,48.530000,18.926667,48.156667,56.490000,...,25.640040,1015,31,1,5,7,24,2016,3,2
17,70,30,20.856667,53.660000,47.056667,20.200000,48.447500,18.890000,47.963333,56.933333,...,24.501307,1560,31,1,5,7,25,2016,4,2
18,80,30,20.890000,51.193333,46.330000,20.200000,48.193333,18.963333,48.630000,57.060000,...,24.656351,1205,31,1,5,7,20,2016,5,2
19,140,40,20.890000,49.800000,46.026667,20.166667,47.633333,19.033333,49.500000,70.726667,...,24.443029,223,31,1,5,7,24,2016,3,1
20,120,20,20.890000,48.433333,45.722500,20.166667,47.300000,19.175000,49.947500,79.000000,...,25.119388,502,31,1,5,7,23,2016,4,6
21,190,40,20.963333,47.633333,45.530000,20.200000,47.026667,19.260000,49.696667,79.730000,...,25.113635,86,31,1,5,7,23,2016,2,4
22,110,40,21.033333,47.063333,45.223333,20.260000,46.826667,19.323333,49.166667,79.256667,...,24.458478,736,31,1,5,7,14,2016,3,5
23,110,40,21.100000,46.596667,44.963333,20.290000,46.633333,19.390000,48.426667,78.393333,...,24.458478,736,31,1,5,7,14,2016,3,5
24,110,30,21.133333,46.060000,44.760000,20.290000,46.433333,19.390000,48.193333,82.460000,...,24.458478,736,31,1,5,7,14,2016,3,5
25,110,20,21.200000,45.800000,44.760000,20.390000,46.223333,19.390000,47.800000,82.590000,...,24.458478,736,31,1,5,7,14,2016,3,5
26,100,30,21.290000,45.900000,45.090000,20.390000,46.090000,19.390000,47.560000,70.990000,...,25.172715,978,31,1,5,7,14,2016,2,6
27,100,20,21.356667,45.826667,45.163333,20.390000,46.090000,19.390000,47.500000,62.430000,...,25.172715,978,31,1,5,7,14,2016,2,6
28,100,20,21.390000,45.690000,45.060000,20.390000,46.090000,19.426667,47.993333,59.030000,...,25.172715,978,31,1,5,7,14,2016,2,6
29,100,20,21.500000,45.333333,44.933333,20.390000,46.060000,19.566667,48.466667,56.726667,...,25.172715,978,31,1,5,7,14,2016,2,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19705,280,0,25.033333,48.363333,40.595714,28.496667,41.900000,24.500000,45.066667,52.900000,...,26.752419,82,29,1,5,7,13,2016,2,4
19706,240,0,25.166667,48.156667,40.940000,28.290000,41.966667,24.500000,45.333333,53.000000,...,25.841169,84,29,1,5,7,22,2016,2,0
19707,250,0,25.323333,47.930000,41.012857,28.200000,42.090000,24.533333,45.566667,53.060000,...,23.687579,77,28,1,5,7,13,2016,2,5
19708,220,0,25.390000,47.656667,41.036000,28.200000,42.030000,24.600000,45.760000,53.200000,...,28.459476,73,27,1,5,7,3,2016,2,4
19709,230,0,25.500000,47.133333,41.000000,28.200000,41.796667,24.600000,45.790000,53.260000,...,26.142286,82,29,1,5,7,16,2016,2,0
19710,190,10,25.500000,47.060000,41.000000,28.200000,41.530000,24.600000,45.863333,53.200000,...,25.113635,86,31,1,5,7,23,2016,2,4
19711,160,0,25.600000,46.990000,41.203750,28.200000,41.590000,24.633333,46.030000,53.200000,...,23.648364,90,28,1,5,7,9,2016,2,2
19712,80,0,25.600000,46.730000,41.384286,28.426667,41.430000,24.700000,46.090000,53.090000,...,24.656351,1205,31,1,5,7,20,2016,5,2
19713,60,0,25.566667,46.633333,41.378000,28.566667,41.156667,24.700000,45.966667,53.030000,...,25.181673,3282,31,1,5,7,12,2016,4,1
19714,60,0,25.500000,46.360000,41.264286,28.566667,40.663333,24.700000,45.826667,52.966667,...,25.181673,3282,31,1,5,7,12,2016,4,1
19715,60,0,25.500000,46.060000,41.000000,28.426667,40.590000,24.666667,45.526667,52.826667,...,25.181673,3282,31,1,5,7,12,2016,4,1
19716,60,0,25.500000,45.933333,41.000000,28.356667,40.560000,24.666667,45.400000,52.645000,...,25.181673,3282,31,1,5,7,12,2016,4,1
19717,70,0,25.500000,45.760000,41.000000,28.290000,40.433333,24.700000,45.363333,52.560000,...,24.501307,1560,31,1,5,7,25,2016,4,2
19718,80,0,25.500000,45.626667,41.000000,28.260000,40.260000,24.700000,45.230000,52.433333,...,24.656351,1205,31,1,5,7,20,2016,5,2
19719,80,0,25.500000,45.590000,41.000000,28.200000,40.126667,24.700000,45.163333,52.290000,...,24.656351,1205,31,1,5,7,20,2016,5,2
19720,70,0,25.500000,45.522500,41.051429,28.200000,40.200000,24.700000,45.163333,52.156667,...,24.501307,1560,31,1,5,7,25,2016,4,2
19721,100,0,25.500000,45.633333,41.196000,28.133333,40.260000,24.700000,45.300000,52.126667,...,25.172715,978,31,1,5,7,14,2016,2,6
19722,100,0,25.500000,45.730000,41.428571,28.100000,40.433333,24.700000,45.433333,52.200000,...,25.172715,978,31,1,5,7,14,2016,2,6
19723,90,0,25.500000,45.790000,41.590000,28.100000,40.560000,24.700000,45.500000,52.090000,...,25.640040,1015,31,1,5,7,24,2016,3,2
19724,100,0,25.500000,45.933333,41.652857,28.000000,40.700000,24.700000,45.466667,52.090000,...,25.172715,978,31,1,5,7,14,2016,2,6
19725,220,0,25.426667,46.060000,41.700000,28.000000,40.760000,24.700000,45.400000,52.060000,...,28.459476,73,27,1,5,7,3,2016,2,4
19726,180,0,25.500000,46.530000,41.725714,27.856667,40.500000,24.700000,45.500000,52.000000,...,26.182685,78,28,1,5,7,16,2016,2,1
19727,120,0,25.500000,47.456667,42.320000,27.663333,40.693333,24.700000,45.560000,52.126667,...,25.119388,502,31,1,5,7,23,2016,4,6
19728,110,0,25.600000,47.193333,42.528571,27.390000,41.030000,24.700000,45.626667,52.260000,...,24.458478,736,31,1,5,7,14,2016,3,5
19729,90,0,25.533333,46.860000,42.534000,27.323333,41.090000,24.700000,45.626667,52.326667,...,25.640040,1015,31,1,5,7,24,2016,3,2
19730,100,0,25.566667,46.560000,42.025714,27.200000,41.163333,24.700000,45.590000,52.400000,...,25.172715,978,31,1,5,7,14,2016,2,6
19731,90,0,25.500000,46.500000,42.080000,27.133333,41.223333,24.700000,45.590000,52.326667,...,25.640040,1015,31,1,5,7,24,2016,3,2
19732,270,10,25.500000,46.596667,42.768571,27.050000,41.690000,24.700000,45.730000,52.266667,...,25.227304,87,28,1,5,7,4,2016,4,0
19733,420,10,25.500000,46.990000,43.036000,26.890000,41.290000,24.700000,45.790000,52.200000,...,24.173328,33,21,1,5,7,16,2016,2,5
19734,430,10,25.500000,46.600000,42.971429,26.823333,41.156667,24.700000,45.963333,52.200000,...,21.247191,25,17,1,5,6,1,2016,2,0

In [27]:
feature_matrix, feature_defs = ft.dfs(entityset=es,target_entity="lights", max_depth=3, verbose=1)

Built 156 features
Elapsed: 00:02 | Remaining: 00:00 | Progress: 100%|██████████████████████████████████████████| Calculated: 10/10 chunks

In [28]:
feature_matrix

,T2,T5,T7,SUM(energydata.lights),SUM(energydata.T1),SUM(energydata.RH_1),SUM(energydata.RH_2),SUM(energydata.T3),SUM(energydata.RH_3),SUM(energydata.T4),...,MEAN(energydata.rv2),COUNT(energydata),NUM_UNIQUE(energydata.DAY(date)),NUM_UNIQUE(energydata.YEAR(date)),NUM_UNIQUE(energydata.MONTH(date)),NUM_UNIQUE(energydata.WEEKDAY(date)),MODE(energydata.DAY(date)),MODE(energydata.YEAR(date)),MODE(energydata.MONTH(date)),MODE(energydata.WEEKDAY(date))
Appliances,,,,,,,,,,,,,,,,,,,,,
10,17.790000,17.100000,17.633333,10,171.310000,388.211667,392.656667,179.220000,377.687500,161.996667,...,18.903283,9,7,1,2,5,28,2016,1,3
20,19.823333,18.700000,17.856667,170,6874.833690,14075.958929,14260.389544,6999.958956,14008.221917,6467.829833,...,24.866657,343,31,1,5,7,27,2016,1,4
30,20.700000,19.200000,17.700000,780,14917.032738,28573.419167,29275.997506,15159.332754,28520.481087,14146.564690,...,25.960188,723,31,1,5,7,18,2016,1,4
40,20.790000,19.200000,17.700000,2730,41808.957522,81469.864211,82956.507901,42672.389541,81010.238017,39666.790947,...,24.878402,2019,31,1,5,7,19,2016,1,1
50,19.200000,17.166667,17.200000,5210,94209.646515,174458.232753,178660.487326,96957.901592,171553.540294,90704.161066,...,25.104459,4368,31,1,5,7,19,2016,4,1
60,19.200000,17.166667,17.200000,10590,72342.927311,131585.699674,134149.038077,74697.939411,127859.407501,70309.903841,...,25.181673,3282,31,1,5,7,12,2016,4,1
70,19.230000,17.100000,17.200000,7880,34206.253911,62253.329592,62556.575831,35122.180663,60458.791107,33152.694830,...,24.501307,1560,31,1,5,7,25,2016,4,2
80,20.200000,17.200000,17.666667,5460,26519.204906,47813.004756,47304.958316,27116.875071,46461.487159,25618.410696,...,24.656351,1205,31,1,5,7,20,2016,5,2
90,20.166667,17.166667,17.760000,5700,22367.864987,40606.643236,39995.960522,22795.713558,39323.172769,21512.522291,...,25.640040,1015,31,1,5,7,24,2016,3,2
100,19.856667,17.100000,17.963333,5730,21694.412697,39718.010959,38903.498476,22064.918410,37888.602407,20785.969887,...,25.172715,978,31,1,5,7,14,2016,2,6
110,20.290000,17.600000,17.633333,4850,16435.430234,29963.077063,29419.850235,16762.282600,28476.245745,15767.171719,...,24.458478,736,31,1,5,7,14,2016,3,5
120,20.200000,18.066667,17.600000,3540,11172.477004,20474.091632,20035.179491,11352.463026,19557.260297,10670.704221,...,25.119388,502,31,1,5,7,23,2016,4,6
130,19.100000,17.856667,17.890000,2720,7322.446872,13405.149190,13162.340889,7415.515910,12875.219180,7005.019457,...,24.175263,330,31,1,5,7,9,2016,3,1
140,20.200000,17.593333,17.600000,2460,4921.778199,9142.037636,8973.129785,4988.455967,8789.707556,4682.689025,...,24.443029,223,31,1,5,7,24,2016,3,1
150,19.000000,17.700000,18.463333,1070,3163.196398,5872.220725,5750.599351,3233.005275,5644.218097,3013.125861,...,24.227941,144,29,1,5,7,24,2016,2,1
160,22.000000,20.893333,18.760000,910,1980.835671,3700.484794,3604.763457,2026.209729,3536.224044,1907.231370,...,23.648364,90,28,1,5,7,9,2016,2,2
170,19.200000,17.963333,17.972500,480,1526.181667,2868.542500,2794.663399,1572.754365,2761.461127,1477.809764,...,25.139818,70,26,1,5,7,14,2016,2,0
180,18.000000,18.222500,17.790000,570,1685.206688,3257.125563,3159.103487,1749.142168,3101.894166,1619.906688,...,26.182685,78,28,1,5,7,16,2016,2,1
190,20.260000,17.666667,17.533333,610,1876.681667,3587.162619,3478.123881,1952.508631,3446.987143,1797.649841,...,25.113635,86,31,1,5,7,23,2016,2,4
200,19.033333,17.790000,18.066667,380,1256.018381,2368.886024,2318.232814,1298.468595,2272.935405,1210.824412,...,22.899091,58,29,1,5,7,12,2016,2,3
210,18.990000,17.600000,18.100000,500,1481.073810,2785.014024,2710.493997,1541.131151,2699.236508,1429.615683,...,29.259321,69,26,1,5,7,4,2016,3,2
220,19.200000,18.000000,17.926667,400,1579.185887,3047.793156,2948.149048,1661.957479,2971.839292,1507.696748,...,28.459476,73,27,1,5,7,3,2016,2,4
230,19.356667,17.100000,17.247500,580,1771.043405,3347.074810,3246.161095,1844.327167,3287.432444,1714.898472,...,26.142286,82,29,1,5,7,16,2016,2,0
240,21.000000,19.200000,17.790000,400,1843.795400,3484.880471,3359.864327,1938.483090,3365.995530,1773.910669,...,25.841169,84,29,1,5,7,22,2016,2,0
250,19.730000,17.100000,17.963333,480,1677.579690,3147.330706,3035.900690,1769.396921,3066.000810,1621.167584,...,23.687579,77,28,1,5,7,13,2016,2,5
260,18.890000,18.000000,17.700000,530,1947.780082,3683.041117,3533.024070,2086.835772,3601.385170,1877.553949,...,23.944205,89,27,1,5,7,4,2016,2,4
270,19.100000,19.323333,18.290000,540,1917.644536,3606.155345,3480.454881,2039.374000,3507.514345,1846.886436,...,25.227304,87,28,1,5,7,4,2016,4,0
280,22.197500,20.790000,18.790000,320,1798.275000,3385.276429,3297.391548,1895.755810,3265.859119,1721.651000,...,26.752419,82,29,1,5,7,13,2016,2,4
290,19.100000,17.856667,17.890000,420,1502.007045,2829.903424,2758.377691,1583.542576,2756.903879,1464.812124,...,23.002045,69,26,1,5,7,15,2016,4,0
300,18.000000,18.260000,17.700000,450,1579.771333,2998.163667,2905.869167,1665.254159,2962.046357,1531.887836,...,23.798485,73,26,1,5,7,8,2016,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
630,19.066667,19.623333,18.290000,70,235.786667,443.260000,426.832500,243.041667,431.898571,221.830000,...,27.433266,11,7,1,5,4,7,2016,3,0
640,22.000000,17.890000,19.100000,50,154.450000,294.530000,299.170000,162.260000,284.963333,146.306667,...,16.783052,7,6,1,4,4,15,2016,4,4
650,22.000000,17.932778,19.022222,70,152.759167,288.370833,290.663333,156.106667,279.676667,142.846667,...,30.848698,7,7,1,4,4,9,2016,2,4
660,17.790000,17.340000,18.600000,80,239.096667,466.743333,450.537976,251.696667,438.392500,230.528095,...,21.739643,11,10,1,5,5,8,2016,3,0
670,20.600000,17.677778,16.862222,30,87.280000,166.216667,164.270000,89.843333,163.586667,83.116667,...,23.250024,4,2,1,3,2,30,2016,1,5
680,17.323333,15.390000,15.600000,80,124.136667,242.216667,228.473333,127.043333,237.320000,123.358095,...,24.335288,6,5,1,4,3,10,2016,3,4
690,18.500000,17.323333,17.500000,70,186.574167,366.070000,362.658333,191.280000,359.941667,176.663333,...,22.302363,9,8,1,4,6,14,2016,2,1
700,22.790000,21.351111,18.856667,60,190.133333,365.670833,359.236667,199.906667,350.177333,180.595833,...,27.333447,9,9,1,3,5,1,2016,2,0
710,17.200000,15.390000,15.600000,120,169.823333,340.436667,320.652000,177.415000,327.115833,169.633333,...,19.836749,8,7,1,5,5,8,2016,2,0
720,19.260000,17.875714,19.100000,50,155.246667,298.876667,281.453333,169.492500,277.214167,154.631667,...,22.998096,7,5,1,3,4,4,2016,4,4
730,22.463333,20.700000,21.290000,0,67.413333,134.830000,130.079167,74.063333,118.816667,64.913333,...,20.341794,3,3,1,1,3,4,2016,4,0
740,20.790000,17.100000,17.566667,50,102.643333,191.700000,186.046667,105.487500,197.576667,98.360000,...,18.387861,5,4,1,3,3,14,2016,1,0
750,21.286429,18.890000,19.716875,80,155.093333,306.090000,293.900000,160.800000,285.970000,150.260000,...,28.859962,7,7,1,3,5,4,2016,4,0
760,17.890000,17.500000,18.500000,50,86.346667,167.183333,160.100000,94.190833,152.222500,82.933333,...,30.406108,4,3,1,2,4,8,2016,3,0
770,19.290000,17.890000,19.000000,20,43.023333,89.263333,80.233333,43.790000,78.386667,45.090000,...,9.271920,2,2,1,2,2,12,2016,2,1
780,21.000000,17.600000,16.890000,0,83.056667,162.720000,168.776667,86.040000,155.113333,80.899167,...,28.392924,4,4,1,3,3,16,2016,3,4
790,21.700000,17.100000,17.700000,20,89.123333,174.950000,161.767576,92.346667,165.316667,85.056667,...,28.900878,4,4,1,3,4,4,2016,1,0
800,20.100000,18.030000,21.412000,20,61.390000,123.950000,121.433939,62.586667,121.213333,61.193333,...,31.889573,3,3,1,2,2,16,2016,1,6
820,21.230000,20.890000,21.390000,0,46.100000,92.126667,81.428095,49.923333,79.983333,46.137143,...,10.918739,2,2,1,2,2,16,2016,4,3
830,16.960000,16.038889,16.100000,10,17.600000,38.090000,38.030000,17.790000,37.390000,16.200000,...,25.791194,1,1,1,1,1,20,2016,1,2
840,20.133333,19.200000,19.200000,0,21.390000,37.700000,38.466667,22.700000,36.590000,19.823333,...,47.772522,1,1,1,1,1,30,2016,4,5
850,16.926667,15.390000,15.600000,20,41.956667,87.793333,80.025714,44.230000,80.623333,42.190000,...,31.571944,2,2,1,2,2,24,2016,1,3
860,19.326667,18.166667,20.390000,0,20.000000,32.730000,33.266667,20.033333,34.696667,20.000000,...,40.254773,1,1,1,1,1,14,2016,3,0
870,22.267500,20.790000,21.830000,0,22.890000,37.590000,35.740000,27.163333,38.066667,22.832857,...,45.527255,1,1,1,1,1,22,2016,4,4
880,20.856667,19.700000,21.856667,10,23.200000,40.530000,41.030000,25.633333,38.260000,20.500000,...,49.270131,1,1,1,1,1,25,2016,3,4
890,18.566667,17.867778,17.235000,20,19.730000,37.863333,34.090000,18.390000,36.863333,17.600000,...,3.221583,1,1,1,1,1,21,2016,1,3
900,22.200000,20.890000,21.790000,0,23.000000,43.166667,40.426667,26.100000,38.930000,21.600000,...,15.105153,1,1,1,1,1,4,2016,4,0
910,20.856667,17.100000,17.600000,0,21.463333,41.693333,38.363333,21.666667,43.930000,18.700000,...,18.937972,1,1,1,1,1,14,2016,1,3
1070,18.426667,17.856667,17.290000,30,19.600000,34.300000,33.963333,18.390000,36.930000,17.700000,...,11.735734,1,1,1,1,1,21,2016,1,3
1080,21.040000,18.890000,19.790000,30,21.930000,42.766667,38.080000,20.700000,40.633333,20.890000,...,27.408521,1,1,1,1,1,16,2016,1,5

In [47]:
y_featuretools = df[['date','Appliances']]
x_featuretools = df.drop(["Appliances"],axis=1)

In [48]:
entities1 = {
    "energy" : (x_featuretools, "date"),"appliances" :(y_featuretools,"date")
}

In [52]:
rel = [("appliances","date","energy","date")]

In [56]:
feature_matrix, feature_defs = ft.dfs(entities=entities1,relationships=rel,target_entity="appliances",verbose=1)

Built 163 features
Elapsed: 03:51 | Remaining: 00:00 | Progress: 100%|██████████████████████████████████████████| Calculated: 11/11 chunks

In [57]:
feature_matrix

,Appliances,SUM(energy.lights),SUM(energy.T1),SUM(energy.RH_1),SUM(energy.T2),SUM(energy.RH_2),SUM(energy.T3),SUM(energy.RH_3),SUM(energy.T4),SUM(energy.RH_4),...,MEAN(energy.T9),MEAN(energy.RH_9),MEAN(energy.T_out),MEAN(energy.Press_mm_hg),MEAN(energy.RH_out),MEAN(energy.Windspeed),MEAN(energy.Visibility),MEAN(energy.Tdewpoint),MEAN(energy.rv1),MEAN(energy.rv2)
date,,,,,,,,,,,,,,,,,,,,,
2016-01-11 17:00:00,60,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,...,17.033333,45.530000,6.600000,733.500000,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
2016-01-11 17:10:00,60,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,...,17.066667,45.560000,6.483333,733.600000,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2016-01-11 17:20:00,50,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,...,17.000000,45.500000,6.366667,733.700000,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
2016-01-11 17:30:00,50,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,...,17.000000,45.400000,6.250000,733.800000,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
2016-01-11 17:40:00,60,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,...,17.000000,45.400000,6.133333,733.900000,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
2016-01-11 17:50:00,50,40,19.890000,46.026667,19.200000,44.500000,19.790000,44.933333,18.890000,45.730000,...,17.000000,45.290000,6.016667,734.000000,92.000000,5.333333,43.833333,4.800000,44.919484,44.919484
2016-01-11 18:00:00,60,50,19.890000,45.766667,19.200000,44.500000,19.790000,44.900000,18.890000,45.790000,...,17.000000,45.290000,5.900000,734.100000,92.000000,5.000000,40.000000,4.700000,47.233763,47.233763
2016-01-11 18:10:00,60,50,19.856667,45.560000,19.200000,44.500000,19.730000,44.900000,18.890000,45.863333,...,17.000000,45.290000,5.916667,734.166667,91.833333,5.166667,40.000000,4.683333,33.039890,33.039890
2016-01-11 18:20:00,60,40,19.790000,45.597500,19.200000,44.433333,19.730000,44.790000,18.890000,45.790000,...,17.000000,45.290000,5.933333,734.233333,91.666667,5.333333,40.000000,4.666667,31.455702,31.455702
2016-01-11 18:30:00,70,40,19.856667,46.090000,19.230000,44.400000,19.790000,44.863333,18.890000,46.096667,...,17.000000,45.290000,5.950000,734.300000,91.500000,5.500000,40.000000,4.650000,3.089314,3.089314
2016-01-11 18:40:00,230,70,19.926667,45.863333,19.356667,44.400000,19.790000,44.900000,18.890000,46.430000,...,17.000000,45.290000,5.966667,734.366667,91.333333,5.666667,40.000000,4.633333,10.298729,10.298729
2016-01-11 18:50:00,580,60,20.066667,46.396667,19.426667,44.400000,19.790000,44.826667,19.000000,46.430000,...,16.890000,45.290000,5.983333,734.433333,91.166667,5.833333,40.000000,4.616667,8.827838,8.827838
2016-01-11 19:00:00,430,50,20.133333,48.000000,19.566667,44.400000,19.890000,44.900000,19.000000,46.363333,...,16.963333,45.290000,6.000000,734.500000,91.000000,6.000000,40.000000,4.600000,34.351142,34.351142
2016-01-11 19:10:00,250,40,20.260000,52.726667,19.730000,45.100000,19.890000,45.493333,19.000000,47.223333,...,16.890000,45.326667,6.000000,734.616667,90.500000,6.000000,40.000000,4.516667,19.205186,19.205186
2016-01-11 19:20:00,100,10,20.426667,55.893333,19.856667,45.833333,20.033333,47.526667,19.000000,48.696667,...,16.890000,45.345000,6.000000,734.733333,90.000000,6.000000,40.000000,4.433333,38.492071,38.492071
2016-01-11 19:30:00,100,10,20.566667,53.893333,20.033333,46.756667,20.100000,48.466667,19.000000,48.490000,...,16.890000,45.326667,6.000000,734.850000,89.500000,6.000000,40.000000,4.350000,24.884962,24.884962
2016-01-11 19:40:00,90,10,20.730000,52.660000,20.166667,47.223333,20.200000,48.530000,18.926667,48.156667,...,16.890000,45.290000,6.000000,734.966667,89.000000,6.000000,40.000000,4.266667,35.880925,35.880925
2016-01-11 19:50:00,70,30,20.856667,53.660000,20.200000,47.056667,20.200000,48.447500,18.890000,47.963333,...,16.890000,45.290000,6.000000,735.083333,88.500000,6.000000,40.000000,4.183333,49.595305,49.595305
2016-01-11 20:00:00,80,30,20.890000,51.193333,20.200000,46.330000,20.200000,48.193333,18.963333,48.630000,...,16.890000,45.200000,6.000000,735.200000,88.000000,6.000000,40.000000,4.100000,19.001759,19.001759
2016-01-11 20:10:00,140,40,20.890000,49.800000,20.200000,46.026667,20.166667,47.633333,19.033333,49.500000,...,16.890000,45.200000,6.000000,735.233333,87.833333,6.000000,40.000000,4.066667,38.872261,38.872261
2016-01-11 20:20:00,120,20,20.890000,48.433333,20.200000,45.722500,20.166667,47.300000,19.175000,49.947500,...,16.890000,45.126667,6.000000,735.266667,87.666667,6.000000,40.000000,4.033333,46.735262,46.735262
2016-01-11 20:30:00,190,40,20.963333,47.633333,20.260000,45.530000,20.200000,47.026667,19.260000,49.696667,...,16.890000,45.126667,6.000000,735.300000,87.500000,6.000000,40.000000,4.000000,10.607126,10.607126
2016-01-11 20:40:00,110,40,21.033333,47.063333,20.290000,45.223333,20.260000,46.826667,19.323333,49.166667,...,16.890000,45.060000,6.000000,735.333333,87.333333,6.000000,40.000000,3.966667,32.583688,32.583688
2016-01-11 20:50:00,110,40,21.100000,46.596667,20.356667,44.963333,20.290000,46.633333,19.390000,48.426667,...,16.890000,45.000000,6.000000,735.366667,87.166667,6.000000,40.000000,3.933333,6.277755,6.277755
2016-01-11 21:00:00,110,30,21.133333,46.060000,20.426667,44.760000,20.290000,46.433333,19.390000,48.193333,...,16.890000,44.966667,6.000000,735.400000,87.000000,6.000000,40.000000,3.900000,13.361033,13.361033
2016-01-11 21:10:00,110,20,21.200000,45.800000,20.500000,44.760000,20.390000,46.223333,19.390000,47.800000,...,16.890000,44.900000,5.933333,735.466667,87.166667,6.000000,40.000000,3.866667,19.305705,19.305705
2016-01-11 21:20:00,100,30,21.290000,45.900000,20.533333,45.090000,20.390000,46.090000,19.390000,47.560000,...,16.890000,44.790000,5.866667,735.533333,87.333333,6.000000,40.000000,3.833333,0.669517,0.669517
2016-01-11 21:30:00,100,20,21.356667,45.826667,20.666667,45.163333,20.390000,46.090000,19.390000,47.500000,...,16.890000,44.790000,5.800000,735.600000,87.500000,6.000000,40.000000,3.800000,19.119398,19.119398
2016-01-11 21:40:00,100,20,21.390000,45.690000,20.700000,45.060000,20.390000,46.090000,19.426667,47.993333,...,16.890000,44.700000,5.733333,735.666667,87.666667,6.000000,40.000000,3.766667,43.484542,43.484542
2016-01-11 21:50:00,100,20,21.500000,45.333333,20.700000,44.933333,20.390000,46.060000,19.566667,48.466667,...,16.890000,44.700000,5.666667,735.733333,87.833333,6.000000,40.000000,3.733333,17.017450,17.017450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-05-27 13:10:00,280,0,25.033333,48.363333,26.528571,40.595714,28.496667,41.900000,24.500000,45.066667,...,23.100000,46.500000,21.250000,756.050000,59.833333,1.166667,23.666667,13.100000,32.420348,32.420348
2016-05-27 13:20:00,240,0,25.166667,48.156667,26.600000,40.940000,28.290000,41.966667,24.500000,45.333333,...,23.100000,46.500000,21.400000,756.000000,59.666667,1.333333,23.333333,13.200000,49.189027,49.189027
2016-05-27 13:30:00,250,0,25.323333,47.930000,26.600000,41.012857,28.200000,42.090000,24.533333,45.566667,...,23.100000,46.522500,21.550000,755.950000,59.500000,1.500000,23.000000,13.300000,15.081162,15.081162
2016-05-27 13:40:00,220,0,25.390000,47.656667,26.600000,41.036000,28.200000,42.030000,24.600000,45.760000,...,23.100000,46.530000,21.700000,755.900000,59.333333,1.666667,22.666667,13.400000,45.226866,45.226866
2016-05-27 13:50:00,230,0,25.500000,47.133333,26.600000,41.000000,28.200000,41.796667,24.600000,45.790000,...,23.100000,46.530000,21.850000,755.850000,59.166667,1.833333,22.333333,13.500000,5.773431,5.773431
2016-05-27 14:00:00,190,10,25.500000,47.060000,26.540000,41.000000,28.200000,41.530000,24.600000,45.863333,...,23.100000,46.530000,22.000000,755.800000,59.000000,2.000000,22.000000,13.600000,41.515044,41.515044
2016-05-27 14:10:00,160,0,25.600000,46.990000,26.512500,41.203750,28.200000,41.590000,24.633333,46.030000,...,23.100000,46.530000,21.966667,755.800000,59.000000,2.000000,21.833333,13.550000,19.540642,19.540642
2016-05-27 14:20:00,80,0,25.600000,46.730000,26.437143,41.384286,28.426667,41.430000,24.700000,46.090000,...,23.100000,46.590000,21.933333,755.800000,59.000000,2.000000,21.666667,13.500000,16.977597,16.977597
2016-05-27 14:30:00,60,0,25.566667,46.633333,26.370000,41.378000,28.566667,41.156667,24.700000,45.966667,...,23.100000,46.626667,21.900000,755.800000,59.000000,2.000000,21.500000,13.450000,8.991420,8.991420
2016-05-27 14:40:00,60,0,25.500000,46.360000,26.318571,41.264286,28.566667,40.663333,24.700000,45.826667,...,23.100000,46.700000,21.866667,755.800000,59.000000,2.000000,21.333333,13.400000,40.409885,40.409885
2016-05-27 14:50:00,60,0,25.500000,46.060000,26.350000,41.000000,28.426667,40.590000,24.666667,45.526667,...,23.100000,46.590000,21.833333,755.800000,59.000000,2.000000,21.166667,13.350000,37.889086,37.889086
2016-05-27 15:00:00,60,0,25.500000,45.933333,26.277143,41.000000,28.356667,40.560000,24.666667,45.400000,...,23.100000,46.590000,21.800000,755.800000,59.000000,2.000000,21.000000,13.300000,17.123315,17.123315
2016-05-27 15:10:00,70,0,25.500000,45.760000,26.200000,41.000000,28.290000,40.433333,24.700000,45.363333,...,23.133333,46.590000,21.966667,755.750000,58.333333,2.000000,21.333333,13.283333,24.058432,24.058432
2016-05-27 15:20:00,80,0,25.500000,45.626667,26.171429,41.000000,28.260000,40.260000,24.700000,45.230000,...,23.133333,46.590000,22.133333,755.700000,57.666667,2.000000,21.666667,13.266667,9.538671,9.538671
2016-05-27 15:30:00,80,0,25.500000,45.590000,26.100000,41.000000,28.200000,40.126667,24.700000,45.163333,...,23.166667,46.590000,22.300000,755.650000,57.000000,2.000000,22.000000,13.250000,30.020685,30.020685
2016-05-27 15:40:00,70,0,25.500000,45.522500,26.100000,41.051429,28.200000,40.200000,24.700000,45.163333,...,23.100000,46.590000,22.466667,755.600000,56.333333,2.000000,22.333333,13.233333,23.851737,23.851737
2016-05-27 15:50:00,100,0,25.500000,45.633333,26.080000,41.196000,28.133333,40.260000,24.700000,45.300000,...,23.200000,46.590000,22.633333,755.550000,55.666667,2.000000,22.666667,13.216667,47.981309,47.981309
2016-05-27 16:00:00,100,0,25.500000,45.730000,26.000000,41.428571,28.100000,40.433333,24.700000,45.433333,...,23.200000,46.590000,22.800000,755.500000,55.000000,2.000000,23.000000,13.200000,18.215602,18.215602
2016-05-27 16:10:00,90,0,25.500000,45.790000,26.000000,41.590000,28.100000,40.560000,24.700000,45.500000,...,23.160000,46.590000,22.833333,755.450000,55.000000,2.166667,22.833333,13.233333,38.751594,38.751594
2016-05-27 16:20:00,100,0,25.500000,45.933333,26.000000,41.652857,28.000000,40.700000,24.700000,45.466667,...,23.200000,46.621429,22.866667,755.400000,55.000000,2.333333,22.666667,13.266667,32.306224,32.306224
2016-05-27 16:30:00,220,0,25.426667,46.060000,26.000000,41.700000,28.000000,40.760000,24.700000,45.400000,...,23.200000,46.700000,22.900000,755.350000,55.000000,2.500000,22.500000,13.300000,23.009520,23.009520
2016-05-27 16:40:00,180,0,25.500000,46.530000,26.000000,41.725714,27.856667,40.500000,24.700000,45.500000,...,23.200000,46.652857,22.933333,755.300000,55.000000,2.666667,22.333333,13.333333,25.296732,25.296732
2016-05-27 16:50:00,120,0,25.500000,47.456667,26.000000,42.320000,27.663333,40.693333,24.700000,45.560000,...,23.200000,46.718000,22.966667,755.250000,55.000000,2.833333,22.166667,13.366667,1.796395,1.796395
2016-05-27 17:00:00,110,0,25.600000,47.193333,25.968571,42.528571,27.390000,41.030000,24.700000,45.626667,...,23.200000,46.751429,23.000000,755.200000,55.000000,3.000000,22.000000,13.400000,18.248201,18.248201
2016-05-27 17:10:00,90,0,25.533333,46.860000,25.978000,42.534000,27.323333,41.090000,24.700000,45.626667,...,23.200000,46.745000,22.866667,755.200000,55.333333,3.166667,22.833333,13.366667,16.966162,16.966162
2016-05-27 17:20:00,100,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,...,23.200000,46.790000,22.733333,755.200000,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
2016-05-27 17:30:00,90,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,...,23.200000,46.790000,22.600000,755.200000,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
2016-05-27 17:40:00,270,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,...,23.200000,46.790000,22.466667,755.200000,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
2016-05-27 17:50:00,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,...,23.200000,46.817500,22.333333,755.200000,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
2016-05-27 18:00:00,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,...,23.200000,46.845000,22.200000,755.200000,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851